spring:
  application:
    name: notification-service

  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
