rootProject.name = 'bubbletea'

include 'common-lib'
include 'common-test'
include 'eureka-server'
include 'config-server'
include 'gateway-server'

include 'auth-service'
include 'user-service'
include 'product-service'
include 'payment-service'
include 'order-service'
include 'notification-service'
include 'chat-service'