package com.bubbletea.notification.entity.enums;

public enum NotificationType {

  PRODUCT_ACTIVATION_SCHEDULED,
  PRODUCT_DELETION_SCHEDULED,
  PRODUCT_PRICE_CHANGE_SCHEDULED,
  PRODUCT_DEACTIVATION_SCHEDULED,
  PRODUCT_OPEN_SCHEDULED,
  PAYMENT_COMPLETE,
  PAYMENT_FAIL,
  MEMBER_SIGNED_UP,
  MEMBER_AUTH_LOGIN,
  MEMBER_PASSWORD_CHANGED,
  MEMBER_DELETE_ACCOUNT,
  CHAT_PUBLISHED,
  SUBSCRIBE_RENEWAL
}
