spring:
  application:
    name: chat-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

cors:
  allowed-origins: "http://localhost:3000,http://localhost:5173,http://localhost:8600,http://localhost:8000"

jwt:
  secret: "default_secret_key_for_chat_service_at_least_32_bytes_long!"
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000


