apply plugin: 'java-library'

dependencies {
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-validation'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}


jar {
    enabled = true
}

tasks.register("prepareKotlinBuildScriptModel"){}